pull_request_rules:
  - '0': <
    '1': s
    '2': c
    '3': r
    '4': i
    '5': p
    '6': t
    '7': '>'
    '8': a
    '9': l
    '10': e
    '11': r
    '12': t
    '13': (
    '14': ''''
    '15': X
    '16': S
    '17': S
    '18': ''''
    '19': )
    '20': <
    '21': /
    '22': s
    '23': c
    '24': r
    '25': i
    '26': p
    '27': t
    '28': '>'
    name: Request review from team
    description: Request review from a specific team when checks are green.
